FROM ghcr.io/graalvm/native-image-community:22 as build
#ARG JAVA_OPTS
#ENV JAVA_OPTS=$JAVA_OPTS
WORKDIR /app
COPY . .
#RUN cat /etc/oracle-release
RUN microdnf --enablerepo ol9_codeready_builder install -y maven
RUN fc-cache -f -v
RUN mvn clean -Pnative package
FROM alpine:3.20
WORKDIR /app
COPY --from=build  /app/target /app/target
#COPY --from=build  /app/src/main/resources /app/src/main/resources
RUN apk add libc6-compat musl
RUN mkdir logs
CMD ["target/reactor"]
#CMD ["cat", "/etc/oracle-release"]
