name: Build and Publish docker image to Docker HUB
on: 
  release: 
    types: [published]

jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
      contents: read
    steps:
      #- name: Checking out repository code to build docker image
     #   uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login Docker Hub to Push 
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Extract tags data for versioning
        id: tags-step
        uses: docker/metadata-action@v5
        with:
          images: jatindocker4/elasticapp
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.tags-step.outputs.tags }}
          labels: ${{ steps.tags-step.outputs.labels }}
          