name: Running building and upload arifact
on: [workflow_dispatch]

jobs:
  running-and-building:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4.2.1
          with:
            distribution: 'corretto'
            java-version: 22
            cache: 'maven'
        - name: Build with Maven
          run: mvn clean -B package --file pom.xml
        - uses: actions/upload-artifact@v4
          with:
            name: upload-artifact
            path: target/webflux-payground-0.0.1-SNAPSHOT.jar
            retention-days: 10